from enum import Enum

class WebSocketEvent(str, Enum):
    PATIENT_UPDATED = "PATIENT_UPDATED"
    QUEUE_UPDATED = "QUEUE_UPDATED"
    ALERT_CREATED = "ALERT_CREATED"
    DETERIORATION = "DETERIORATION"
    CAPACITY_UPDATED = "CAPACITY_UPDATED"
    OVERRIDE_APPLIED = "OVERRIDE_APPLIED"
    SYSTEM = "SYSTEM"
