import { Patient, QueuePatient, Alert, Capacity, AuditEvent } from '@/types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'P001',
    name: 'James Wilson',
    age: 34,
    gender: 'male',
    chiefComplaint: 'Minor laceration on hand',
    symptoms: ['laceration', 'minor_bleeding'],
    medicalHistory: [],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 90 * 60000).toISOString(),
    status: 'WAITING',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    latestAssessment: {
      id: 'A001',
      priority: 'LOW',
      riskScore: 5,
      confidence: 0.92,
      safetyFlags: [],
      reasons: [{ code: 'LACERATION', message: 'Minor laceration, no systemic involvement' }],
      recommendedAction: 'ROUTINE_REVIEW',
      deteriorating: false,
      ageGroup: 'ADULT',
      createdAt: new Date(Date.now() - 88 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 72, systolicBp: 120, diastolicBp: 78,
      spo2: 98, temperature: 36.8, respiratoryRate: 14,
      timestamp: new Date(Date.now() - 88 * 60000).toISOString(),
    },
  },
  {
    id: 'P002',
    name: 'Margaret Chen',
    age: 58,
    gender: 'female',
    chiefComplaint: 'Chest pain radiating to left arm',
    symptoms: ['chest_pain', 'shortness_of_breath', 'nausea', 'weakness'],
    medicalHistory: ['hypertension', 'diabetes'],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'IN_REVIEW',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
    latestAssessment: {
      id: 'A002',
      priority: 'CRITICAL',
      riskScore: 83,
      confidence: 0.89,
      safetyFlags: ['LOW_BLOOD_PRESSURE_CRITICAL', 'LOW_OXYGEN_SATURATION', 'RESPIRATORY_DISTRESS'],
      reasons: [
        { code: 'CHEST_PAIN', message: 'Critical symptom: chest pain' },
        { code: 'LOW_BP', message: 'Systolic BP critically low at 88mmHg' },
        { code: 'LOW_SPO2', message: 'SpO2 low at 91%' },
      ],
      recommendedAction: 'IMMEDIATE_CLINICIAN_REASSESSMENT',
      deteriorating: false,
      ageGroup: 'ADULT',
      safetyFloor: 'CRITICAL',
      createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 118, systolicBp: 88, diastolicBp: 56,
      spo2: 91, temperature: 37.1, respiratoryRate: 26,
      timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    },
  },
  {
    id: 'P009',
    name: 'Carlos Rivera',
    age: 62,
    gender: 'male',
    chiefComplaint: 'Breathlessness and weakness',
    symptoms: ['shortness_of_breath', 'weakness', 'palpitations'],
    medicalHistory: ['hypertension', 'heart_failure'],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 25 * 60000).toISOString(),
    status: 'WAITING',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    latestAssessment: {
      id: 'A009',
      priority: 'HIGH',
      riskScore: 72,
      confidence: 0.81,
      safetyFlags: ['RESPIRATORY_DISTRESS', 'ABNORMAL_HEART_RATE'],
      reasons: [
        { code: 'RESPIRATORY_DISTRESS', message: 'Respiratory rate elevated at 24/min' },
        { code: 'ELEVATED_HEART_RATE', message: 'Heart rate elevated at 108bpm' },
        { code: 'MEDICAL_HISTORY', message: 'Relevant history: heart failure' },
      ],
      recommendedAction: 'URGENT_CLINICIAN_REVIEW',
      deteriorating: false,
      ageGroup: 'ADULT',
      createdAt: new Date(Date.now() - 23 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 108, systolicBp: 101, diastolicBp: 65,
      spo2: 95, temperature: 37.8, respiratoryRate: 24,
      timestamp: new Date(Date.now() - 23 * 60000).toISOString(),
    },
    vitalHistory: [
      {
        id: 'V009A', patientId: 'P009',
        heartRate: 95, systolicBp: 115, diastolicBp: 74,
        spo2: 97, temperature: 37.5, respiratoryRate: 20,
        timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
      },
      {
        id: 'V009B', patientId: 'P009',
        heartRate: 108, systolicBp: 101, diastolicBp: 65,
        spo2: 95, temperature: 37.8, respiratoryRate: 24,
        timestamp: new Date(Date.now() - 23 * 60000).toISOString(),
      },
    ],
  },
  {
    id: 'P004',
    name: 'Sofia Patel',
    age: 8,
    gender: 'female',
    chiefComplaint: 'High fever and difficulty breathing',
    symptoms: ['fever', 'shortness_of_breath', 'cough', 'fatigue'],
    medicalHistory: ['asthma'],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 20 * 60000).toISOString(),
    status: 'IN_TREATMENT',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    latestAssessment: {
      id: 'A004',
      priority: 'CRITICAL',
      riskScore: 82,
      confidence: 0.85,
      safetyFlags: ['CRITICAL_HEART_RATE', 'RESPIRATORY_DISTRESS_CRITICAL', 'LOW_OXYGEN_SATURATION'],
      reasons: [
        { code: 'PEDIATRIC_HR', message: 'Heart rate critically elevated for pediatric patient at 148bpm' },
        { code: 'RESPIRATORY', message: 'Respiratory rate critically elevated at 34/min' },
        { code: 'LOW_SPO2', message: 'SpO2 below normal at 93%' },
      ],
      recommendedAction: 'IMMEDIATE_CLINICIAN_REASSESSMENT',
      deteriorating: false,
      ageGroup: 'PEDIATRIC',
      safetyFloor: 'CRITICAL',
      createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 148, systolicBp: 90, diastolicBp: 58,
      spo2: 93, temperature: 39.2, respiratoryRate: 34,
      timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    },
  },
  {
    id: 'P005',
    name: 'Harold Thompson',
    age: 78,
    gender: 'male',
    chiefComplaint: 'Confusion and weakness since this morning',
    symptoms: ['confusion', 'weakness', 'dizziness', 'altered_mental_status'],
    medicalHistory: ['hypertension', 'diabetes', 'stroke', 'chronic_kidney_disease'],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 35 * 60000).toISOString(),
    status: 'WAITING',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    latestAssessment: {
      id: 'A005',
      priority: 'HIGH',
      riskScore: 47,
      confidence: 0.78,
      safetyFlags: ['LOW_OXYGEN_SATURATION'],
      reasons: [
        { code: 'ALTERED_MENTAL_STATUS', message: 'Symptom: altered mental status' },
        { code: 'AGE_GERIATRIC', message: 'Geriatric patient (78y)' },
        { code: 'MEDICAL_HISTORY', message: 'History of stroke increases risk' },
      ],
      recommendedAction: 'URGENT_CLINICIAN_REVIEW',
      deteriorating: false,
      ageGroup: 'GERIATRIC',
      createdAt: new Date(Date.now() - 33 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 98, systolicBp: 158, diastolicBp: 96,
      spo2: 94, temperature: 38.1, respiratoryRate: 22,
      timestamp: new Date(Date.now() - 33 * 60000).toISOString(),
    },
  },
  {
    id: 'P006',
    name: 'Unknown Patient',
    age: 52,
    gender: 'male',
    chiefComplaint: 'Unresponsive, found by paramedics',
    symptoms: ['altered_mental_status', 'shortness_of_breath'],
    medicalHistory: null,
    historyAvailable: false,
    arrivalTime: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'IN_TREATMENT',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    latestAssessment: {
      id: 'A006',
      priority: 'CRITICAL',
      riskScore: 76,
      confidence: 0.48,
      safetyFlags: ['LOW_BLOOD_PRESSURE', 'LOW_OXYGEN_SATURATION', 'RESPIRATORY_DISTRESS'],
      reasons: [
        { code: 'ALTERED_MENTAL_STATUS', message: 'Altered mental status' },
        { code: 'LOW_CONFIDENCE', message: 'Assessment confidence limited due to incomplete data' },
        { code: 'UNKNOWN_HISTORY', message: 'Medical history unavailable - treating conservatively' },
      ],
      recommendedAction: 'IMMEDIATE_CLINICIAN_REASSESSMENT',
      deteriorating: false,
      ageGroup: 'ADULT',
      safetyFloor: 'CRITICAL',
      createdAt: new Date(Date.now() - 14 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 122, systolicBp: 94, diastolicBp: 60,
      spo2: 92, temperature: 38.5, respiratoryRate: 28,
      timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
    },
  },
  {
    id: 'P003',
    name: 'Robert Kim',
    age: 45,
    gender: 'male',
    chiefComplaint: 'Moderate back pain',
    symptoms: ['back_pain', 'muscle_spasm'],
    medicalHistory: ['hypertension'],
    historyAvailable: true,
    arrivalTime: new Date(Date.now() - 45 * 60000).toISOString(),
    status: 'WAITING',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 42 * 60000).toISOString(),
    latestAssessment: {
      id: 'A003',
      priority: 'LOW',
      riskScore: 8,
      confidence: 0.88,
      safetyFlags: [],
      reasons: [{ code: 'BACK_PAIN', message: 'Reported symptom: back pain' }],
      recommendedAction: 'ROUTINE_REVIEW',
      deteriorating: false,
      ageGroup: 'ADULT',
      createdAt: new Date(Date.now() - 42 * 60000).toISOString(),
    },
    latestVitals: {
      heartRate: 88, systolicBp: 135, diastolicBp: 88,
      spo2: 97, temperature: 37.0, respiratoryRate: 16,
      timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
    },
  },
];

export const MOCK_QUEUE: QueuePatient[] = [
  {
    id: 'P002', name: 'Margaret Chen', age: 58, gender: 'female',
    chiefComplaint: 'Chest pain radiating to left arm',
    priority: 'CRITICAL', riskScore: 83, confidence: 0.89,
    waitMinutes: 5, deteriorating: false,
    safetyFlags: ['LOW_BLOOD_PRESSURE_CRITICAL', 'LOW_OXYGEN_SATURATION'],
    reasons: [{ code: 'CHEST_PAIN', message: 'Critical symptom: chest pain' }],
    recommendedAction: 'IMMEDIATE_CLINICIAN_REASSESSMENT',
    queuePosition: 1,
  },
  {
    id: 'P004', name: 'Sofia Patel', age: 8, gender: 'female',
    chiefComplaint: 'High fever and difficulty breathing',
    priority: 'CRITICAL', riskScore: 82, confidence: 0.85,
    waitMinutes: 20, deteriorating: false,
    safetyFlags: ['CRITICAL_HEART_RATE', 'RESPIRATORY_DISTRESS_CRITICAL'],
    reasons: [{ code: 'PEDIATRIC_CRITICAL', message: 'Pediatric patient with critical vitals' }],
    recommendedAction: 'IMMEDIATE_CLINICIAN_REASSESSMENT',
    queuePosition: 2,
  },
  {
    id: 'P009', name: 'Carlos Rivera', age: 62, gender: 'male',
    chiefComplaint: 'Breathlessness and weakness',
    priority: 'HIGH', riskScore: 72, confidence: 0.81,
    waitMinutes: 25, deteriorating: false,
    safetyFlags: ['RESPIRATORY_DISTRESS'],
    reasons: [{ code: 'RESPIRATORY_DISTRESS', message: 'Respiratory rate elevated' }],
    recommendedAction: 'URGENT_CLINICIAN_REVIEW',
    queuePosition: 3,
  },
  {
    id: 'P005', name: 'Harold Thompson', age: 78, gender: 'male',
    chiefComplaint: 'Confusion and weakness',
    priority: 'HIGH', riskScore: 47, confidence: 0.78,
    waitMinutes: 35, deteriorating: false,
    safetyFlags: ['LOW_OXYGEN_SATURATION'],
    reasons: [{ code: 'ALTERED_MENTAL_STATUS', message: 'Altered mental status in geriatric patient' }],
    recommendedAction: 'URGENT_CLINICIAN_REVIEW',
    queuePosition: 4,
  },
  {
    id: 'P003', name: 'Robert Kim', age: 45, gender: 'male',
    chiefComplaint: 'Moderate back pain',
    priority: 'LOW', riskScore: 8, confidence: 0.88,
    waitMinutes: 45, deteriorating: false,
    safetyFlags: [],
    reasons: [{ code: 'BACK_PAIN', message: 'Back pain, stable vitals' }],
    recommendedAction: 'ROUTINE_REVIEW',
    queuePosition: 5,
  },
  {
    id: 'P001', name: 'James Wilson', age: 34, gender: 'male',
    chiefComplaint: 'Minor laceration on hand',
    priority: 'LOW', riskScore: 5, confidence: 0.92,
    waitMinutes: 90, deteriorating: false,
    safetyFlags: [],
    reasons: [{ code: 'LACERATION', message: 'Minor laceration' }],
    recommendedAction: 'ROUTINE_REVIEW',
    queuePosition: 6,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'AL001',
    patientId: 'P002',
    type: 'SYSTEM',
    severity: 'CRITICAL',
    message: 'CRITICAL: Margaret Chen has critical safety flags: LOW_BLOOD_PRESSURE_CRITICAL, LOW_OXYGEN_SATURATION',
    metadata: { flags: ['LOW_BLOOD_PRESSURE_CRITICAL', 'LOW_OXYGEN_SATURATION'], priority: 'CRITICAL' },
    acknowledged: false,
    createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
    resolvedAt: null,
  },
  {
    id: 'AL002',
    patientId: 'P009',
    type: 'DETERIORATION',
    severity: 'WARNING',
    message: 'DETERIORATION DETECTED: Carlos Rivera vitals worsening',
    metadata: { previousPriority: 'MODERATE', newPriority: 'HIGH' },
    acknowledged: false,
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    resolvedAt: null,
  },
  {
    id: 'AL003',
    patientId: null,
    type: 'CAPACITY',
    severity: 'WARNING',
    message: 'CAPACITY: ED at 82% capacity. Critical beds at 90%.',
    metadata: { utilization: 0.82, criticalUtilization: 0.90 },
    acknowledged: false,
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    resolvedAt: null,
  },
];

export const MOCK_CAPACITY: Capacity = {
  totalBeds: 50,
  occupiedBeds: 41,
  availableBeds: 9,
  criticalBeds: 10,
  criticalOccupied: 9,
  criticalAvailable: 1,
  utilization: 0.82,
  criticalUtilization: 0.90,
  status: 'WARNING',
  warningMessage: 'Critical care capacity severely constrained: 1 bed remaining',
};

export const MOCK_QUEUE_RESPONSE = {
  patients: MOCK_QUEUE,
  totalCount: MOCK_QUEUE.length,
  criticalCount: MOCK_QUEUE.filter(p => p.priority === 'CRITICAL').length,
  highCount: MOCK_QUEUE.filter(p => p.priority === 'HIGH').length,
  moderateCount: MOCK_QUEUE.filter(p => p.priority === 'MODERATE').length,
  lowCount: MOCK_QUEUE.filter(p => p.priority === 'LOW').length,
  updatedAt: new Date().toISOString(),
};

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'AU001', patientId: 'P009', eventType: 'PATIENT_CREATED',
    actor: 'SYSTEM', description: 'Patient Carlos Rivera registered. Initial triage: HIGH',
    metadata: { priority: 'HIGH', riskScore: 72 },
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'AU002', patientId: 'P009', eventType: 'TRIAGE_COMPLETED',
    actor: 'SYSTEM', description: 'Triage completed for Carlos Rivera: Priority=HIGH, Risk=72.0',
    metadata: { priority: 'HIGH', riskScore: 72, confidence: 0.81 },
    createdAt: new Date(Date.now() - 23 * 60000).toISOString(),
  },
  {
    id: 'AU003', patientId: 'P009', eventType: 'DETERIORATION_DETECTED',
    actor: 'SYSTEM', description: 'Deterioration detected for Carlos Rivera: SpO2 decreased by 6.0%',
    metadata: { changes: ['SpO2 decreased', 'Heart rate increased', 'BP dropped'] },
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'AU004', patientId: 'P009', eventType: 'ASSESSMENT_UPDATED',
    actor: 'SYSTEM', description: 'Assessment updated: Priority changed HIGH → CRITICAL',
    metadata: { previousPriority: 'HIGH', newPriority: 'CRITICAL' },
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'AU005', patientId: 'P009', eventType: 'ALERT_CREATED',
    actor: 'SYSTEM', description: 'Alert: DETERIORATION DETECTED for Carlos Rivera',
    metadata: { alertType: 'DETERIORATION', severity: 'CRITICAL' },
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
];
